# main.py — Generated by VIA for: Build a full stack application for a school to manage students, attendance, and grades. The app should have a beautiful, modern dashboard where teachers can add new students, mark daily attendance (present/absent), and log test scores. Make sure the data is saved securely to the database so it persists after refreshing.
from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from database import engine, get_db
from models import Base, Item
from sqlalchemy.orm import Session
import os

app = FastAPI(
    title="Build A Full Stack Application For",
    description="Generated by VIA — Autonomous AI Digital Team",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.on_event("startup")
def on_startup():
    try:
        Base.metadata.create_all(bind=engine)
    except Exception as e:
        import logging as _log
        _log.getLogger("via").warning(f"DB init warning: {e}")

questions_data = [
    {"id": 1, "question": "What comes next: 2, 4, 8, 16, ?", "options": ["24","32","28","20"], "answer": "32", "category": "Pattern"},
    {"id": 2, "question": "All Bloops are Razzles, all Razzles are Lazzles. All Bloops are Lazzles?", "options": ["True","False"], "answer": "True", "category": "Logic"},
    {"id": 3, "question": "Odd one out: 3, 5, 11, 14, 23, 29?", "options": ["3","5","14","29"], "answer": "14", "category": "Numbers"},
    {"id": 4, "question": "5 + 3 × 2 = ?", "options": ["16","11","13","10"], "answer": "11", "category": "Numerical"},
    {"id": 5, "question": "Book:Reading :: Fork:?", "options": ["Cooking","Eating","Kitchen","Food"], "answer": "Eating", "category": "Verbal"},
]

@app.get("/")
def root():
    return {"app": "Build A Full Stack Application For", "status": "running", "generated_by": "VIA"}

@app.get("/health")
def health():
    return {"status": "healthy"}


@app.get("/api/v1/questions")
def get_questions():
    return questions_data

@app.post("/api/v1/submit")
def submit_score(payload: dict, db: Session = Depends(get_db)):
    score = payload.get("score", 0)
    total = payload.get("total", len(questions_data))
    pct   = round((score / total) * 100, 1) if total else 0
    if pct >= 90:   iq_level = "Genius (IQ 140+)"
    elif pct >= 80: iq_level = "Very Intelligent (IQ 120-139)"
    elif pct >= 70: iq_level = "Intelligent (IQ 110-119)"
    elif pct >= 60: iq_level = "Above Average (IQ 100-109)"
    else:           iq_level = "Average (IQ 90-99)"
    db_item = Item(title=payload.get("player", "Anonymous"), description=f"Score:{score}/{total}|{iq_level}", status=iq_level)
    db.add(db_item); db.commit()
    return {"score": score, "total": total, "percentage": pct, "iq_level": iq_level}

@app.get("/api/v1/items")
def get_items(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    items = db.query(Item).offset(skip).limit(limit).all()
    return {"items": [{"id": i.id, "title": i.title, "description": i.description,
                       "status": i.status, "created_at": str(i.created_at)} for i in items],
            "total": db.query(Item).count()}

@app.get("/api/v1/items/{item_id}")
def get_item(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"id": item.id, "title": item.title, "description": item.description,
            "status": item.status, "created_at": str(item.created_at)}

@app.post("/api/v1/items")
def create_item(payload: dict, db: Session = Depends(get_db)):
    item = Item(title=payload.get("title", "Untitled"),
                description=payload.get("description", ""),
                status=payload.get("status", "active"))
    db.add(item); db.commit(); db.refresh(item)
    return {"id": item.id, "title": item.title, "description": item.description,
            "status": item.status, "created_at": str(item.created_at)}

@app.put("/api/v1/items/{item_id}")
def update_item(item_id: int, payload: dict, db: Session = Depends(get_db)):
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    for key, val in payload.items():
        if hasattr(item, key):
            setattr(item, key, val)
    db.commit(); db.refresh(item)
    return {"id": item.id, "title": item.title, "description": item.description, "status": item.status}

@app.delete("/api/v1/items/{item_id}")
def delete_item(item_id: int, db: Session = Depends(get_db)):
    item = db.query(Item).filter(Item.id == item_id).first()
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    db.delete(item); db.commit()
    return {"deleted": item_id}

@app.get("/api/v1/stats")
def get_stats(db: Session = Depends(get_db)):
    total = db.query(Item).count()
    return {"total": total, "active": total, "categories": list(set(q["category"] for q in questions_data))}

# ── Route aliases: /api/v1/students and /students mirror /api/v1/items ────
@app.get("/api/v1/students")
def alias_get_students(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return get_items(skip=skip, limit=limit, db=db)

@app.post("/api/v1/students")
def alias_create_students(payload: dict, db: Session = Depends(get_db)):
    return create_item(payload=payload, db=db)

@app.get("/api/v1/students/{item_id}")
def alias_get_students_one(item_id: int, db: Session = Depends(get_db)):
    return get_item(item_id=item_id, db=db)

@app.put("/api/v1/students/{item_id}")
def alias_update_students(item_id: int, payload: dict, db: Session = Depends(get_db)):
    return update_item(item_id=item_id, payload=payload, db=db)

@app.delete("/api/v1/students/{item_id}")
def alias_delete_students(item_id: int, db: Session = Depends(get_db)):
    return delete_item(item_id=item_id, db=db)

@app.get("/students")
def alias_get_students_short(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    return get_items(skip=skip, limit=limit, db=db)

@app.post("/students")
def alias_create_students_short(payload: dict, db: Session = Depends(get_db)):
    return create_item(payload=payload, db=db)

@app.get("/students/{item_id}")
def alias_get_students_short_one(item_id: int, db: Session = Depends(get_db)):
    return get_item(item_id=item_id, db=db)

@app.put("/students/{item_id}")
def alias_update_students_short(item_id: int, payload: dict, db: Session = Depends(get_db)):
    return update_item(item_id=item_id, payload=payload, db=db)

@app.delete("/students/{item_id}")
def alias_delete_students_short(item_id: int, db: Session = Depends(get_db)):
    return delete_item(item_id=item_id, db=db)


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port, reload=False)
